# Generated by Django 5.2.9 on 2025-12-11 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caballo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('edad', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caballos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Caballos',
            },
        ),
        migrations.CreateModel(
            name='ControlVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('condicion_corporal', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('alimentacion', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('caballo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='usuarios.caballo')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Controles Veterinarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
