# Generated by Django 5.2.9 on 2025-12-11 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_caballo_controlveterinario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaPetisero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('limpieza_cascos', models.BooleanField(default=False)),
                ('revision_herraduras', models.BooleanField(default=False)),
                ('tratamiento_cascos', models.BooleanField(default=False)),
                ('aplicacion_aceite', models.BooleanField(default=False)),
                ('revision_herraje', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('caballo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_petisero', to='usuarios.caballo')),
                ('petisero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tareas Petisero',
                'ordering': ['-fecha'],
            },
        ),
    ]
