# Generated by Django 5.2.9 on 2025-12-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_tareapetisero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareapetisero',
            name='ejercicios_prescritos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tareapetisero',
            name='limpieza_heridas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tareapetisero',
            name='medicacion',
            field=models.BooleanField(default=False),
        ),
    ]
