# Generated by Django 5.2.9 on 2025-12-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_tareapetisero_ejercicios_prescritos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('veterinario', 'Veterinario'), ('petisero', 'Petisero'), ('administrador', 'Administrador'), ('cliente', 'Cliente'), ('entrenador', 'Entrenador')], max_length=20, unique=True),
        ),
    ]
