# Generated by Django 5.2.9 on 2025-12-11 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_rol_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_entrenamiento', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('caballo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='usuarios.caballo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_cliente', to=settings.AUTH_USER_MODEL)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_entrenador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clases de Entrenamiento',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
